name: Pipeline de CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Bajar el c√≥digo (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Instalar dependencias
        run: npm install

      # ESTE ES EL PASO NUEVO, EN EL LUGAR CORRECTO:
      - name: Arreglar permisos de Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: 4. Ejecutar las pruebas
        run: npm test
